### PR TITLE
Added f-strings to Chapters 8 and 9

### PR DESCRIPTION
**Pull request by spamegg1**
***Data migration warning!*** Deleted 2 steps from Chapter 8, first page "Introducing Nested Loops"
- also did a few `TODO message` steps

### CODE REVIEW

**Comment by alexmojaki** [comment]
Excellent work! Your message step was fine, you just found a bug in the API. Are you happy to merge?

**Comment by spamegg1** [comment]
Yes, happy to merge!
I was actually going to tell you... I suspected a bug because... I changed the `check` method to:
```python
def check(self):
    return True
```
and it still would not trigger the message step! Sorry I should have told you earlier.

**Comment by alexmojaki** [comment]
> I know ExerciseStep implements check based on solution but I did not know if MessageStep overrode it.

It doesn't. You can look at the source to check.

**Comment by alexmojaki** [comment]
Checked that no one was on the deleted steps.

**Comment by spamegg1** [comment]
What next?

**Comment by alexmojaki** [comment]
Think about how to explain nested lists: accessing and setting indices, and looping over them. I will create an issue with some of my thoughts.

**Pull request merged**
