### PR TITLE
Re-style toc page

### PR DESCRIPTION
**Pull request by pwwang**
Make it something look like:

image

### CODE REVIEW

**Comment by alexmojaki** [comment]
It looks nice, but wasn't part of the goal to make something less bright? It's even brighter than before, definitely a bit of a shock after the dark home page.

Do you think the instructions should be kept? I think they can probably be removed, except for the "You were last on the page" case.

**Comment by pwwang** [comment]
Yeah, haven't noticed the transition from the dark homepage. Will try to make it darker.

Possible to make the instructions shorter?

**Comment by pwwang** [comment]
How about this:

image

**Comment by alexmojaki** [comment]
I think it's good! I'm going to merge now because it's already a definite improvement.

I'm not sure what to do about the instructions, it's actually fine as it is but I'm open to ideas.

"You were last on the page" looks a bit weird, is that intentional?

Screenshot from 2021-04-03 13-14-17

The font size for the page links seems a bit small?

We now have three different dark backgrounds for the home page, ToC, and login. Maybe we need some consistency?

@spamegg1 @ChrisjanWust any thoughts?

**Pull request merged**
