### PR TITLE
Chapter about quotes and f-strings #61

### PR DESCRIPTION
**Pull request by spamegg1**
- added `c07_a_bit_more_about_strings.py`
- renumbered `nested_loops`, `functions` and `boolean_operators` chapters
- tweaked some exercises in `c06_lists.py`

### CODE REVIEW

**Comment by spamegg1** [comment]
Some issues remain:

How to use `__copyable__` with plain text that doesn't follow Python syntax?
```
    __copyable__
    Special cases aren't special enough to break the rules.
```
gives
```
File "/usr/src/app/backend/main/utils/__init__.py", line 168, in run
    node.set("class", node.get("class") + " copyable")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

- Similar issue with the broken program exercise at the very end of f-strings page.
- Could not figure out how to include broken string `'Alice's Diner'` and make the build pass. Does it need a `Step` with a manual `check` method?

**Comment by alexmojaki** [comment]
> How to use `__copyable__` with plain text that doesn't follow Python syntax?

Looks like a bug. Try fixing it!

>  Does it need a Step with a manual check method?

Yes, a verbatim step requires valid syntax.

**Comment by spamegg1** [comment]
OK, I was able to fix the `'Alice's Diner'` issue. I hope `return "SyntaxError" in self.result` is good enough of a check! 

However now `__program_indented__` does not get syntax highlighting. I assume this is normal behavior, as in Chapter 4:
```
for character in name:
print(character)
```

Still working on the `__copyable__` issue. I assume when you say "bug" you mean in my code, not in the API. According to the error `node.get("class")` is returning `None` when it shouldn't??? Still trying to understand what nodes are.

**Comment by alexmojaki** [comment]
> I hope return "SyntaxError" in self.result is good enough of a check!

It's a start, but try making it more robust.

> However now __program_indented__ does not get syntax highlighting. I assume this is normal behavior, as in Chapter 4:

Invalid syntax doesn't get highlighted, that's actually related to the copyable bug.

> Still working on the `__copyable__` issue. I assume when you say "bug" you mean in my code, not in the API. According to the error node.get("class") is returning None when it shouldn't??? Still trying to understand what nodes are.

No it's a bug in my code. Node means HTML node. It doesn't have a class so it returns None. Try `node.get("class", "")` or `node.get("class") or ""`.

**Comment by spamegg1** [comment]
I've tried `node.get("class", "") or ""` but now I get:
```
File "/usr/src/app/backend/main/text.py", line 249, in __init__
    assert "__copyable__" not in str(cls.step_texts)
AssertionError
```

If I comment out the `assert` statement obviously the build passes but it breaks things (`__copyable__` is displayed on top of the text, also gets copied)

**Comment by alexmojaki** [comment]
Try actually learning how the code works. See what happens when the syntax is valid. This is a great opportunity to learn and to contribute to the actual functionality in addition to course content.

**Comment by spamegg1** [comment]
Yeah that's true, it's really hard though.

**Comment by alexmojaki** [comment]
OK, I'm done. Let me know if you're fine with the changes. You can see my changes by clicking on the specific commits.

**Comment by alexmojaki** [comment]
Also please add those message steps.

**Comment by spamegg1** [comment]
Changes all look good. Your text makes things clearer, also gives fewer hints for the final exercise.

Do you think "replacing the concatenation (`+`) with an f-string" might be a bit confusing? There are multiple `+`s and they might think they have to replace each one with an `f`. Maybe I'm overthinking this.

We decided to skip the message steps, anything else I should do?

**Comment by alexmojaki** [comment]
I think you're right, how about

> Fix this by replacing all the string concatenations (+) with a single f-string

**Comment by spamegg1** [comment]
OK let me commit that.

**Comment by alexmojaki** [comment]
Awesome! You've now done two full chapters!

Now to replace all prints with multiple arguments with f-strings.

**Comment by spamegg1** [comment]
> Now to replace all prints with multiple arguments with f-strings.

Right!

**Comment by alexmojaki** [comment]
In the nested loops chapter, the first three steps can be reduced to two or maybe even just one.

**Comment by spamegg1** [comment]
OK, I'll open an issue first with markdown drafts.

**Pull request merged**
