### PR TITLE
Nested lists pages #100

### PR DESCRIPTION
**Pull request by spamegg1**
#100

### CODE REVIEW

**Comment by spamegg1** [comment]
How about this? If not we can revert the commit.

**Comment by spamegg1** [comment]
OK, so you went with removing `book` and changing the lengths of sublists in `numbers` to compensate (the empty sublist is also a nice touch there.). That is fine with me. I wasn't a fan of the `book` idea to begin with. It is shorter and flows better now. Is there anything else you want? I'm happy to merge.

By the way why is this needed? `predicted_output_choices = None` To clear the shell from the previous step?

**Comment by alexmojaki** [comment]
It's because that step inherits from the previous step.

I need to review the last bit of the chapter before merging.

How do you feel about the chapter as a whole?

What made you decide to remove the bit about `strings[2].append(x)`? I'm undecided about it.

**Comment by spamegg1** [comment]
Ah I get it now... When I moved `book` to the second page, it didn't occur to me to simply change that text to `strings[2].append(`... I was fixated on moving that mention from the final text of the first page to somewhere in the second page (where `book` was moved). Seeing I couldn't do that, I removed it! 

It's good as a whole, I'll add that back into the final text again.

**Comment by alexmojaki** [comment]
Ready to merge when you are.

Next task will be to update the `diagonal_winner` exercise to use a nested list.

**Comment by spamegg1** [comment]
:+1:

**Pull request merged**
