### PR TITLE
Keep GitHub Actions up to date with GitHub's Dependabot

### PR DESCRIPTION
**Pull request by cclauss**
Auto-generates pull requests to update out-of-date GitHub Actions
* https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
* https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem

### CODE REVIEW

**Comment by cclauss** [comment]
Unclear why it is failing... Closing.

**Comment by cclauss** [comment]
This is blocked by:
* FirebaseExtended/action-hosting-deploy#337

**Comment by alexmojaki** [comment]
The firebase preview is an old problem. I'd happily accept a PR which either solves it or just doesn't try building previews for forks, but it doesn't need to block this. If you reopen here, I'll merge.

**Comment by cclauss** [comment]
Generated:
* #454

**Pull request merged**
