### PR TITLE
Pyodide

### PR DESCRIPTION
**Pull request by alexmojaki**
Not quite ready yet, but I'm at least confident that this is going to work. In short, futurecoder will run Python code in the browser, which will drastically reduce cost and scalability issues.

### CODE REVIEW

**Comment by alexmojaki** [comment]
@spamegg1 @ChrisjanWust @matan-h check it out! All the user code is now run in the browser, not the server. Once everything is loaded you can even disconnect your internet and continue the course! This completely changes the roadmap for futurecoder and gets rid of a lot of problems. No more SET_LIMITS or complicated threads and processes - stuff that especially caused a lot of trouble for @matan-h recently.

The big caveats are:

1. It takes a while to download and initialise everything. On my computer it's a few seconds, but it'll depend on your internet and CPU. I'm curious to hear other people's experiences.
2. input() doesn't work yet, but that should be solvable.
3. Browser support is limited, for example Safari probably won't work.

**Comment by pwwang** [comment]
Exciting!
Does that mean we don't need any backend thing anymore?
Just wondering what takes so long to load? Looks like [Pyodide's link](https://pyodide.org/en/stable/console.html) is pretty fast.

A heroku link to share for me or others to try?

**Comment by spamegg1** [comment]
Awesome! Doing things client-side is a great advantage. (Reminds me of my old number theory project using Brython)
@alexmojaki Congrats on such a huge milestone. `Files changed: 57` Yikes! Must have been difficult. Gets me motivated to continue with my drafts!

On Firefox: opening a page from TOC:
```
Python initialization complete pyodide.asm.js:9:236650
loadPyodide: 12642.38ms - timer ended Worker.5137703f.worker.js:1:13858
Python core ready! pyodide.asm.js:9:236650
load_package_buffer(buffer): 2194.35ms - timer ended Worker.5137703f.worker.js:1:14662
```
My internet is pretty garbage (1MB/s) so keep that in mind.

There seems to be a short 1-2 second hang after a predicted output choice exercise and the confetti animation.

@pwwang Click on "View Deployment"

**Comment by pwwang** [comment]
I didn't feel any delay in loading, strikingly. All worked smoothly for me.

Sounds good?
image

**Comment by alexmojaki** [comment]
> Exciting!
> Does that mean we don't need any backend thing anymore?

Yes, the long term plan is:

1. Make it usable completely offline, as long as static assets have been downloaded.
2. Use something like Cloud Firestore or some serverless BaaS thing (still learning about this) to store user data and do simple database operations. That's all the server does now, nothing complicated left.
3. Serve all static assets from a CDN.

I think that should make it basically infinitely scalable for a low price.

The codebase should still allow running Python on a server for:

1. Easier local development and testing.
2. An application that users can download and install locally with a proper Python interpreter that runs faster and can do things Pyodide can't like access the local filesystem.

> Just wondering what takes so long to load? Looks like [Pyodide's link](https://pyodide.org/en/stable/console.html) is pretty fast.

For me at least Pyodide itself takes longer to load than my code. It's not that long, but if someone has a slow computer it might be a problem.

**Comment by alexmojaki** [comment]
> On Firefox: opening a page from TOC:
> 
> ```
> Python initialization complete pyodide.asm.js:9:236650
> loadPyodide: 12642.38ms - timer ended Worker.5137703f.worker.js:1:13858
> Python core ready! pyodide.asm.js:9:236650
> load_package_buffer(buffer): 2194.35ms - timer ended Worker.5137703f.worker.js:1:14662
> ```
> 
> My internet is pretty garbage (1MB/s) so keep that in mind.

I only just noticed that `loadPyodide: 12642` has 5 digits so I was wondering why you said the second time was faster. So that's a pretty decent demo of why slow internet could be a problem. Nice to see the cache works well.

> There seems to be a short 1-2 second hang after a predicted output choice exercise and the confetti animation.

That's an intentional delay that's alway been there - give the user a moment to process their correct answer before it disappears.

**Comment by alexmojaki** [comment]
> I didn't feel any delay in loading, strikingly. All worked smoothly for me.

The page loads first and then the Python stuff starts loading in the background. So users won't wait long before they can see something and start interacting, and they'll only notice a delay from Pyodide if they try to run code before it finishes loading. If they take their time reading text then they shouldn't notice anything, unless it takes up significant RAM or CPU resources. I don't know if that's an actual concern or not.

**Comment by spamegg1** [comment]
>     2\. Use something like Cloud Firestore or some serverless BaaS thing (still learning about this) to store user data and do simple database operations. That's all the server does now, nothing complicated left.

I wonder if browser local storage or cookies can be used to keep track of which page/step the user was on last, and get rid of email/password/login completely?

**Comment by alexmojaki** [comment]
> I wonder if browser local storage or cookies can be used to keep track of which page/step the user was on last, and get rid of email/password/login completely?

Client side storage will definitely be used, but you could ask the same question about many online services. I think it's pretty commonly accepted that it's important for data to be saved remotely so that users can access it from multiple devices or in case they lose their local data somehow. 

But yes, not requiring login is important, hence #41 is pinned.

**Comment by pwwang** [comment]
> Yes, the long term plan is:
> 
> 1. Make it usable completely offline, as long as static assets have been downloaded.

And

> I wonder if browser local storage or cookies can be used to keep track of which page/step the user was on last, and get rid of email/password/login completely?

keep me thinking about making it completely standalone with something like Electron.

**Comment by alexmojaki** [comment]
Like I said, a local standalone version will use a server with a normal Python interpreter, not Pyodide. Otherwise there's not much point.

**Comment by ChrisjanWust** [comment]
Super cool that this is possible. 

Re:

> The codebase should still allow running Python on a server for:
> 
> Easier local development and testing.
> An application that users can download and install locally with a proper Python interpreter that runs faster and can do things Pyodide can't like access the local filesystem.

I don't quite follow the arguments for keeping the Python server, given that user data is going to be stored on a BaaS (new word for me too :grin: ). Easier local development and testing is, at least in my mind, less important than keeping the development and production environments as similar as possible. And also something that can be improved. What features does access to the filesystem allow for?

**Comment by alexmojaki** [comment]
User data will also be on the BaaS in local development. The server will essentially only be for running code. I'll probably switch it to flask, not much need for Django.

Main advantage for local development is that it reloads code easily. Currently you have to run a script which zips up all the relevant Python code, refresh the page so that it downloads the new zip, and wait for pyodide to load again. I imagine that can be automated and improved to an extent, we'll see once we actually get there.

If at some point the course teaches users how to read and write files, we can teach that with Pyodide's virtual in-memory filesystem. But I think there's value in students interacting with actual files on their own machine and experiencing 'the real thing'.

Some other things that can't be done with Pyodide, at least not 'really' (I think):

- Threads and multiprocessing
- subprocess, e.g. run a shell command
- Servers (e.g. flask/django)
- Make network requests, e.g. talk to an API or scrape a website
- Install arbitrary packages from pypi

But all of this is looking very far ahead.

Then there's the issue of speed. Pure Python code runs about 10x slower in the browser. Most of the time this won't really matter, but it might become an issue for slow computers, complicated user code, or birdseye/snoop. Again, we'll see.

**Comment by alexmojaki** [comment]
:confetti_ball:

**Pull request merged**
