### PR TITLE
docs(README): update controls section

### LINKED ISSUE #44: Update Controls section of README
https://github.com/alexmojaki/futurecoder#controls is a bit out of date now, it should be updated to reflect the changes in #38

### PR DESCRIPTION
**Pull request by BobAnkh**
I have updated Controls section in README with changes mentioned in #38 .

This closes #44 

Please review it to see if I missed something necessary.

### CODE REVIEW

**Comment by alexmojaki** [comment]
Thanks, this is a good start. However my main concern is that the first paragraph in the existing instructions is outdated and needs to be fixed. The new stuff should be merged into that.

**Comment by BobAnkh** [comment]
Ok, I will fix it.

I'm not sure if you just want to give a brief introduction of your core concept when I updated the changes. Now I will try to reorganize this section.

**Comment by BobAnkh** [comment]
@alexmojaki Please review again.

I have updated it. Reorganize the first paragraph but not sure if it covers all things necessary.

**Comment by alexmojaki** [comment]
Thanks for your help. I'll make some final changes from here.

**Pull request merged**
