### PR TITLE
Get page/step from frontend, not database, allowing multiple open pages at once

### LINKED ISSUE #43: Get current page from the frontend instead of the database when running and checking code
The backend gets the current page from the user object in the database and uses that to check if the code passes the current step. This means that if the user has two pages open, trying to complete a step on one of them will fail. Instead the frontend JS should send through the current page index when running code.

### PR DESCRIPTION
**Pull request by alexmojaki**
Closes #43 

This changes a whole bunch of things so it needs testing badly. @spamegg1, @BobAnkh please play with the deployed environment and test it thoroughly if you can. Test running code, navigating between pages, moving steps in developer mode, hints, solutions, make sure that the editor/snoop/pythontutor are shown and hidden at the right times, open multiple tabs at different pages and make sure you can interact with them independently.

### CODE REVIEW

**Comment by spamegg1** [comment]
@alexmojaki Will do.

**Comment by alexmojaki** [comment]
Thanks @spamegg1. In case it's not clear, I'm asking if you can test it out now, not after I merge. Opening this PR automatically deployed it to a new environment to test before making it live. Click "View Deployment to check it out. Let me know if you spot any problems before I merge. You can login with admin@example.com, password "admin".

I've just pushed another commit which gives a proper bonus challenge at the end of the BuildingUpStrings page. Before it was just described in the text, now it's a proper exercise with hints and stuff. At the same time it provides a link to easily skip to the next page. It's a bit of a hacky solution to #21 and nonlinear content in general but I think it's a good start. Let me know what you think.

**Comment by spamegg1** [comment]
Ah OK, I misunderstood. Saw the View Deployment link, will check it out.

**Comment by spamegg1** [comment]
Everything seems to be working fine. Used it on multiple tabs, etc.

The "Reveal" button at the end of a Hint sequence seems to do nothing. After clicking "Yes" on the "Are you sure..." question, it displays the solution and the Reveal button. If I click the Reveal button 25-30 times it disappears.

I'm still having the "Oops, you need to set word = 'Hello' before we can continue." issue.

**Comment by BobAnkh** [comment]
I have also tested the deployment. 

> Test running code, navigating between pages, moving steps in developer mode, hints, solutions, make sure that the editor/snoop/pythontutor are shown and hidden at the right times, open multiple tabs at different pages and make sure you can interact with them independently

I have tested these things. Using Light Mode, so everything works fine to me, LOL.

Forget where the issue mentioned by @spamegg1 locates, so I haven't tested it.

**Comment by alexmojaki** [comment]
Great, thanks for testing guys. Also see how I implemented the bonus challenge at the end of the BuildingUpStrings page. New possibilities are opening up!

> I'm still having the "Oops, you need to set word = 'Hello' before we can continue." issue.

What's the issue? You have to define the variable to use it. Did you define it and it disappeared a short while later?

**Comment by spamegg1** [comment]
Yep, checked out the bonus after Building up Strings, very cool.

> Did you define it and it disappeared a short while later?

Yep. Might be some subtle browser/extension thing. Let's not worry about it.

**Comment by alexmojaki** [comment]
No, the browser shouldn't have anything to do with it. See if you can figure out how to reproduce it.

**Pull request merged**
