### PR TITLE
Upgrading things

### PR DESCRIPTION
**Pull request by alexmojaki**

### CODE REVIEW

**Comment by alexmojaki** [comment]
@spamegg1 fix the test transcript again for 3.9 and try to get the Dockerfile to build

**Comment by spamegg1** [comment]
Sure...
It says `E: Unable to locate package python3.9-dev`. I think that might be unavailable on Ubuntu 18.04. Is this still using Ubuntu 18.04? We might have to switch the image to use Ubuntu 20.04 instead. Or we might have to use `deadsnakes-ppa` maybe.

**Comment by spamegg1** [comment]
Build passes but Deployment doesn't work. I can't access Heroku logs...
Not sure what to do...

**Comment by alexmojaki** [comment]
I don't know what it means, but here's the log:

```
+ python manage.py migrate
Traceback (most recent call last):
  File "/usr/src/app/backend/manage.py", line 28, in <module>
    main()
  File "/usr/src/app/backend/manage.py", line 24, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 387, in check
    all_issues = self._run_checks(
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/commands/migrate.py", line 65, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.9/dist-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/usr/local/lib/python3.9/dist-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/usr/local/lib/python3.9/dist-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/dist-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.9/dist-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/dist-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/src/app/backend/book/urls.py", line 19, in <module>
    import main.urls
  File "/usr/src/app/backend/main/urls.py", line 21, in <module>
    from main.views import FrontendAppView, HomePageView, api_view, timeout_view
  File "/usr/src/app/backend/main/views.py", line 10, in <module>
    import birdseye.server
  File "/usr/local/lib/python3.9/dist-packages/birdseye/server.py", line 19, in <module>
    from flask_humanize import Humanize
  File "/usr/local/lib/python3.9/dist-packages/flask_humanize/__init__.py", line 15, in <module>
    import humanize
  File "/usr/local/lib/python3.9/dist-packages/humanize/__init__.py", line 2, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 559, in _build_master
    ws = cls()
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 552, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 608, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2063, in find_on_path
    for dist in factory(fullpath):
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2128, in distributions_from_metadata
    yield Distribution.from_location(
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2588, in from_location
    return cls(
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2989, in _reload_version
    md_version = self._get_version()
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2770, in _get_version
    version = _version_from_file(lines)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2554, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2765, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 1906, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 1893, in get_metadata
    with io.open(self.path, encoding='utf-8', errors="replace") as f:
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3/dist-packages/.wh.urllib3-1.25.8.egg-info'
```

**Comment by alexmojaki** [comment]
Try reverting the `poetry.lock` file and then running `poetry update libsass gevent` to only update those packages.

**Comment by alexmojaki** [comment]
I'm a little worried that I don't know what those files are and why they're there...

Anyway, at least the site runs. Try to break it, use all the debuggers, advance through a few steps, and make it show some nice tracebacks.

**Comment by spamegg1** [comment]
Here is one traceback, is this normal?
tr01

**Comment by spamegg1** [comment]
Been using the deployment for about an hour. Everything seems OK! I used all the debuggers.
Some nice tracebacks:
tr03
tr04

**Comment by alexmojaki** [comment]
OK, this is great news, but I still want to be sure of dryenv and particularly asttokens first, as mentioned in #140

**Pull request merged**
