### PR TITLE
updated README to include Windows instructions #123

### PR DESCRIPTION
**Pull request by spamegg1**

### CODE REVIEW

**Comment by spamegg1** [comment]
Eh... stupid Markdown formatting issues

**Comment by spamegg1** [comment]
Nope... still looks wrong.

**Comment by alexmojaki** [comment]
Do you think Windows developers need to be told how to run Powershell scripts? I'm not familiar with Powershell at all, is it not standard knowledge? If they can't figure that much out I'm not hopeful about them being able to do much else.

SET_LIMITS needs to be mentioned explicitly somewhere, users aren't supposed to run setup.ps1 every time they start the server. It has other uses anyway, like making it possible to use debuggers within the workers.

**Comment by alexmojaki** [comment]
Also please check the last two steps, I think they're out of date. They shouldn't need to go straight to the login URL, right?

**Comment by spamegg1** [comment]
I'm guessing that someone who is just starting to get into development on Windows would not know how to run Powershell scripts. Powershell scripting is definitely not common knowledge (I was a 20 year long Windows user). The Windows world is more sharply separated by professional/corporate vs. casual user (whereas the average Linux user is generally more capable/knowledgeable). They would start opening issues complaining why setup doesn't work... I'm just saving future headache. If you want to attract some Windows contributors there will be a lot of hand holding.

Can you tell me what the last two steps should be? `npm start` directly launches `localhost:3000` doesn't it? I usually can't follow or understand the order of what happens next.

**Comment by alexmojaki** [comment]
OK I'll take care of the final steps. Happy to merge?

**Comment by spamegg1** [comment]
Sure thing.

**Pull request merged**
